/***************************************************************

  BayCom(R)        Packet-Radio fuer IBM PC

  OpenBayCom-Mailbox

  --------------------------------------------------
  Definitionen fuer internationale Meldungen der Box
  --------------------------------------------------


  Copyright (C)       Florian Radlherr
                      Taubenbergstr. 32
                      83627 Warngau

  Alle Rechte vorbehalten / All Rights Reserved

 ***************************************************************/


#ifdef __FLAT__

#define STDLANG "msg/messages.gb"
static char stdmsg_init[]=
"English v1.07.01\n"
"\"SEND not possible, file system is being processed.\\n\"\n"
"\"Board %s is not possible\\n\"\n"
"\"Message will not be forwarded.\\n\"\n"
"\"Warning: Forward address unknown, no forwarding of this message.\\n\"\n"
"\"Subject >\"\n"
"\"Enter text for %s \"\n"
"\"%s\\nEnding with NNNN or /EX or CTRL-Z, abort with /AB or CTRL-X :\\n\"\n"
"\"%d lines stored for %s\"\n"
"\"\\n\"\n"
"\"\\aNew mail arrived from %s, No.%u, for you\\n\"\n"
"\"No message stored.\\n\"\n"
"\"BID already exists.\\n\"\n"
"\"%s \"\n"
"\"is unknown, no forwarding.\\n\"\n"
"\"is known, forward to \"\n"
"\"OpenBCM messages.gb DH8YMB\\n\"\n"
"\"causes no forwarding.\\n\"\n"
"\"Syntax: PATH <address>\\n\"\n"
"\"Address %s is unknown.\\n\"\n"
"\"Please reenter command with message number or range.\\n\"\n"
"\"erased\"\n"
"\"unerased\"\n"
"\"forwarded\"\n"
"\"Syntax: FORWARD <board> <scope> @<address>\\n\"\n"
"\"set to new lifetime\"\n"
"\"Syntax: SETLIFE <board> <scope> #<days>\\n\"\n"
"\"transferred\"\n"
"\"Syntax: TRANSFER <board> <scope> <newboard>\\n\"\n"
"\"Permission denied.\\n\"\n"
"\"Message will be %s.\\n\"\n"
"\"%d messages will be %s.\\n\"\n"
"\"No such message found.\\n\"\n"
"\"Erase message\"\n"
"\"Message will be erased.\\n\"\n"
"\"Message is erased.\\n\"\n"
"\"Board %s is unknown.\\n\"\n"
"\"Directory of stored Usermails:\\n\"\n"
"\"Directory of all Bulletin-Boards:\\n\"\n"
"\"Board             Lifetime Mails last for\\n\"\n"
"\"\\nDirectory of %s\"\n"
"\"No \"\n"
"\"From   \"\n"
"\"To       \"\n"
"\"Date  \"\n"
"\"Time  \"\n"
"\"Lines\"\n"
"\"Bytes \"\n"
"\"BID           \"\n"
"\"LT  \"\n"
"\"Forw.  \"\n"
"\"Subject\\n\"\n"
"\"No message found, last stored message is:\\n\"\n"
"\"No unread messages found for %s.\\n\"\n"
"\"No messages found for %s.\\n\"\n"
"\"Directory of all User Messages:\\n\"\n"
"\"Directory of Bulletins since %s:\\n\"\n"
"\"Searching for \\\"%s\\\":\\n\"\n"
"\"No messages found.\\n\"\n"
"\"List of all Forward Partners:\\n\"\n"
"\"@       \"\n"
"\"There are not more than %ld entries in the check file.\\n\"\n"
"\"The check file is being rebuilt, please retry later.\\n\"\n"
"\"Log entries \"\n"
"\"No matching entry found.\\n\"\n"
"\"%lu entries found.\\n\"\n"
"\"1 entry found.\\n\"\n"
"\"Current news from %s:\\n\"\n"
"\"No current news.\\n\"\n"
"\"Hello %s, \"\n"
"\"Helplevel = %u, Lines = %u, \"\n"
"\"last login %s\"\n"
"\"first login.\"\n"
"\"\\nPlease enter your Home-BBS by typing \\\"A F <boxcall>\\\"\\n\"\n"
"\"%s is disabled due to maintenance, please retry later.\\n\"\n"
"\"User busy or not logged on.\\n\"\n"
"\"*** %s to %s, end with /q\\n\"\n"
"\"*** %s ended.\\n\"\n"
"\"*** User busy\\n\"\n"
"\"Syntax: %s <call> <message>\\n\"\n"
"\"\\nYour maximum daily data amount (%u kBytes) has been exceeded.\\n\"\n"
"\"Today you may not READ/SEND further bulletins.\\n\"\n"
"\"Invalid command: %s\\n\"\n"
"\"Possible commands are:\\n\"\n"
"\"Syntax: MYBBS <home-BBS>\\n\"\n"
"\"Syntax: NAME <name>\\n\"\n"
"\"Syntax: SEND <call|board> <@address> [#<LT>] <subject>\\n\"\n"
"\"Issue a READ-command before REPLY.\\n\"\n"
"\"Directory %s not found.\\n\"\n"
"\"Cannot forward to my own boxcall!\\n\"\n"
"\"Incorrect date.\\n\"\n"
"\"Syntax: WALL <text>\\n\"\n"
"\"Help Dir Read Erase Check REPly Send Alter Quit\\n\"\n"
"\"Your Home-BBS is set to %s.\\n\"\n"
"\"This information is forwarded to other BBS.\\n\"\n"
"\"never logged on.\"\n"
"\"Parameters of %s: (see HELP ALTER)\\n\"\n"
"\"Home-BBS.......(A F).%c%-18s\"\n"
"\"Reject-boards..(A R).%s\\n\"\n"
"\"Prompt.........(A P).%s\\n\"\n"
"\"Login-command..(A C).%-20s\"\n"
"\"Name........(A N).%s\\n\"\n"
"\"Language.......(A S).%-20s\"\n"
"\"Lines.......(A L).%u\\n\"\n"
"\"Helplevel......(A H).%-20u\"\n"
"\"Linefeeds..(A LF).%u\\n\"\n"
"\"Info-dir......(A ID).%-20s\"\n"
"\"User-dir...(A UD).%s\\n\"\n"
"\"Info-list.....(A IL).%-20s\"\n"
"\"User-list..(A UL).%s\\n\"\n"
"\"Info-read.....(A IR).%-20s\"\n"
"\"User-read..(A UR).%s\\n\"\n"
"\"Check-opt.....(A CH).%-20s\"\n"
"\"No help file found.\\n\"\n"
"\"Name...........(A N).%s\\n\"\n"
"\"Last D N...(Check)...%s\\n\"\n"
"\"Last QUIT............%s\\n\"\n"
"\"Last login...........%s\"\n"
"\"Logins %lu, mails received %lu, read %lu, sent %lu\\n\"\n"
"\"%s is unknown.\\n\"\n"
"\"Options \\\"%s\\\" are set for \"\n"
"\"\\n\"\n"
"\"Unknown option, see HELP ALTER.\\n\"\n"
"\"Current address: %s\\n\"\n"
"\"Please enter BBS address.\\n\"\n"
"\"Invalid address\\n\"\n"
"\"Command too long\\n\"\n"
"\"Please think about this input.\\n\"\n"
"\"Login-command \\\"%s\\\" stored.\\n\"\n"
"\"Prompt too long.\\n\"\n"
"\"Prompt stored.\\n\"\n"
"\"Password too long.\\n\"\n"
"\"Password deleted.\\n\"\n"
"\"Current length: %d characters.\\n\"\n"
"\"Reenter a value within 0..2!\\n\"\n"
"\"Helplevel %d selected.\\n\"\n"
"\"Reenter a value within -1..5!\\n\"\n"
"\"No empty line set.\\n\"\n"
"\"One empty line set.\\n\"\n"
"\"%d empty lines set.\\n\"\n"
"\"Pagebrake off\\n\"\n"
"\"Pagebrake set to %u lines.\\n\"\n"
"\"Reenter value within 0 (off) or 4..100.\\n\"\n"
"\"All your parameters will be set to default values.\\n\"\n"
"\"Do you really want to erase your setup\"\n"
"\"Please reenter important values like Alter Forward!\\n\"\n"
"\"Name too long, please reenter.\\n\"\n"
"\"Hello %s, your name is stored.\\n\"\n"
"\"Too many boardnames.\\n\"\n"
"\"Rejected boards:\\n%s\\n\"\n"
"\"English language (%s) selected.\\n\"\n"
"\"Possible language choices:\\n\"\n"
"\"Current userstate for %s is set to: %u.\\n\"\n"
"\"Present quota is set to %lu kBytes.\\n\"\n"
"\"Current read/send Status %lu kBytes.\\n\"\n"
"\"The maximum quota is at %u kBytes per day.\\n\"\n"
"\"%s? (Y/N) >\"\n"
"\"\\n*** Aborted.\\n\"\n"
"\"Help index:\\n\"\n"
"\"Helptext \\\"%s.%s\\\" not found, see HELP INDEX\\n\"\n"
"\"Board %s will be purged.\\n\"\n"
"\"%u file(s) processed: %u erased, %u obsolete.\\n\"\n"
"\"Transfer of %s not possible.\\n\"\n"
"\"Message has been processed.\\n\"\n"
"\"%d messages have been processed.\\n\"\n"
"\"Not allowed.\\n\"\n"
"\"Command %s not available.\\n\"\n"
"\"Command not available via HTTP.\\n\"\n"
"\"Command not available without password.\\n\"\n"
"\"Option not available without password.\\n\"\n"
"\"Board name too short for completition.\\n\"\n"
"\"File \\\"%s\\\" not found.\\n\"\n"
"\"Missing file name.\\n\"\n"
"\"Can't open file: %s\\n\"\n"
"\"File exists, abort with CTRL-Z.\\n\"\n"
"\"File \\\"%s\\\" already exists.\\n\"\n"
"\"Now waiting for %s file \\\"%s\\\".\\n\"\n"
"\"No file stored.\\n\"\n"
"\"Unable to remove old file, tempfile is \\\"%s\\\"\\n\"\n"
"\"Error writing to output file \\\"%s\\\"\\n\"\n"
"\"File \\\"%s\\\" stored.\\n\"\n"
"\"File \\\"%s\\\" is 0 bytes long.\\n\"\n"
"\"CRC error, no file stored.\\n\"\n"
"\"Welcome to FileSurf.\\n\\n\"\n"
"\"Sorry, FileSurf not enabled.\\n\"\n"
"\"FileSurf terminated. Good bye.\\n\"\n"
"\"Available directories:\\n\"\n"
"\"Sorry, cannot write here!\\n\"\n"
"\"Access to \\\"%s\\\" denied.\\n\"\n"
"\"\\n%d file(s) found.\\n\"\n"
"\"Sorry, input too long.\\n\"\n"
"\"Sorry - path/filename is too long, please contact your sysop.\\n\"\n"
"\"Files in directory: %s\\n\"\n"
"\"Filemask: %s\\n\\n\"\n"
"\"Sorry, directory too complex!\\n\"\n"
"\"<OldName> <NewName>\\n\"\n"
"\"Drive %s not available.\\n\"\n"
"\"BMAIL feature is disabled by sysop, use BGET instead!\\n\"\n"
"\"Current path: %s\\n\"\n"
"\"Sorry, not implemented yet!\\n\"\n"
"\"File\"\n"
"\"Directory\"\n"
"\"Error!\\n\"\n"
"\"Moving\"\n"
"\"Copying\"\n"
"\" %s to %s.\\n\"\n"
"\"File or directory %s already exists.\\n\"\n"
"\"Directory %s created.\\n\"\n"
"\"Directory %s could not be created.\\n\"\n"
"\"Directory %s deleted.\\n\"\n"
"\"Directory %s could not be deleted.\\n\"\n"
"\"Directory %s does not exist.\\n\"\n"
"\"File %s deleted.\\n\"\n"
"\"File %s could not be deleted.\\n\"\n"
"\"File %s does not exist.\\n\"\n"
"\"<Filename>\"\n"
"\"<Directory name>\"\n"
"\"FWDEDIT: too many destinations.\\n\"\n"
"\"FWDEDIT: too many partners.\\n\"\n"
"\"Unknown option %c.\\n\"\n"
"\"Commands\"\n"
"\"Home\"\n"
"\"User\"\n"
"\"Userlogin\"\n"
"\"Create account\"\n"
"\"Remove cookie\"\n"
"\"Mail\"\n"
"\"List usermail\"\n"
"\"Send mail to sysop\"\n"
"\"Send mail\"\n"
"\"Check boards\"\n"
"\"Set checktime\"\n"
"\"Newest 300 mails\"\n"
"\"Board overview\"\n"
"\"OpenBCM News\"\n"
"\"System\"\n"
"\"Login stats\"\n"
"\"System logging\"\n"
"\"S&F stats\"\n"
"\"Stuck usermail\"\n"
"\"Unknown BBS\"\n"
"\"Show processes\"\n"
"\"Current users\"\n"
"\"Version\"\n"
"\"Help\"\n"
"\"Help index\"\n"
"\"Help for newbies\"\n"
"\"\\nForward queue of %s:\\n\"\n"
"\"Error reading %s!\\n\"\n"
"\"Error writing %s!\\n\"\n"
"\"No start-line found in %s %u.\\n\"\n"
"\"Invalid start-line found in %s %u!\\n\"\n"
"\"Invalid BIN-Header in %s %u!\\n\"\n"
"\"Missing filename in BIN-Header, \"\n"
"\"Can't create filename!\\n\"\n"
"\"Creating filename: %s\\n\"\n"
"\"7+-File %s extracted from %s %u.\\n\"\n"
"\"Error %d writing BIN-File %s: %s!\\n\"\n"
"\"BIN-File %s extracted (%lu/%lu Bytes) from %s %u.\\n\"\n"
"\"Not enough memory!\\n\"\n"
"\"%u users, %u found.\\n\"\n"
"\"Directory of all known usercalls:\\n\"\n"
"\"Directory of all locally known usercalls:\\n\"\n"
"\"user3.dat or user3.idx not found.\\n\"\n"
"\"%u calls imported, %u errors.\\n\"\n"
"\"File exists, data will be appended without check.\\n\"\n"
"\"Now waiting for YAPP-file %s\\n\"\n"
"\"NR received\"\n"
"\"*** YAPP-RX aborted: \"\n"
"\"*** YAPP-TX aborted: \"\n"
"\"without CN\"\n"
"\"\nYAPP-TX complete, but no AT received\\n\"\n"
"\"%s-RX OK (%lu bit/s)\\n\"\n"
"\"%s-TX OK (%lu bit/s)\\n\"\n"
"\"Incoming BIDs:\"\n"
"\"*** %s: user not logged on.\\n\"\n"
"\"*** %s: %d lines pending.\\n\"\n"
"\"*** %s: too many lines pending.\\n\"\n"
"\"Too many entries in convert.bcm!\"\n"
"\"All entries in convert.bcm are now alphanumerical sorted.\"\n"
"\"Added: %s -> %s\"\n"
"\"Deleted: %s -> %s\"\n"
"\"convert.bcm is created.\"\n"
"\"Warning: New board may not exist.\"\n"
"\"Warning: Old board exists.\"\n"
"\"\"%s\" not found.\\n\"\n"
"\"%s: line %d error.\\n\"\n"
"\"Forward partner %s already exists!\\n\"\n"
"\"New entry %s added.\\n\"\n"
"\"No valid callsign: %s\\n\"\n"
"\"Entry %s removed.\\n\"\n"
"\"Option %s set.\\n\"\n"
"\"Option %s deleted.\\n\"\n"
"\"Forward partner callsign changed to %s.\\n\"\n"
"\"Forward partner %s not found in fwd.bcm.\\n\"\n"
"\"Entry %s already exists.\\n\"\n"
"\"Entry %s added.\\n\"\n"
"\"Entry %s not found.\\n\"\n"
"\"Cannot delete this boxcall.\\n\"\n"
"\"No valid timestring: %s\\n\"\n"
"\"Forward cpnnectpath to long!\\n\"\n"
"\"Forward time for %s changed to %s.\\n\"\n"
"\"Forward connectpath for %s changed to %s.\\n\"\n"
"\"%d matching lines.\\n\"\n"
"\"Bad regular expression.\\n\"\n"
"\"Importing forward file %s from %s.\\n\"\n"
"\"Import terminated, bad import file.\\n\"\n"
"\"Exporting forward file %s for %s.\\n\"\n"
"\"More than %d entries found, too much for me... aborting.\\n\\n\"\n"
"\"Note: You are currently marked as away, disable now? (Y/N):\"\n"
"\"%s: seems no valid mail file (boardname\\n\"\n"
"\"%s: seems no valid mail file (BID not found)\\n\"\n"
"\"%s: seems no valid mail file (BID)\\n\"\n"
"\"Board TMP/%s created.\\n\"\n"
"\"%s: Board %s, BID $%s is already known, skipping mail.\\n\"\n"
"\"%s: Board %s, BID $%s is new, importing mail.\\n\"\n"
"\"REORG F started...\\n\"\n"
"\"%u file(s) scanned, %u imported, %u skipped, %u errors.\\n\"\n"
"\"Purge disabled.\\n\"\n"
"\"PURGE (whole file system) started.\\n\"\n"
"\"PURGE/REORG is already running. Retry later!\\n\"\n"
"\"Lifetime must be between 0 and 999, not %s.\\n\"\n"
"\"No runutils active.\\n\"\n"
"\"%d runutils active.\\n\"\n"
"\"DieBox userfile import started...\\n\"\n"
"\"Old mail import started in directory \\\"%s\\\"...\\n\"\n"
"\"Beacon process started.\\n\"\n"
"\"%d beacon frames sent.\\n\"\n"
"\"Flexnet configuration upload started.\\n\"\n"
"\"REORG invoked.\\n\"\n"
"\"POSTFWD invoked.\\n\"\n"
"\"Login call changed.\\n\"\n"
"\"Box disabled.\\n\"\n"
"\"Box enabled.\\n\"\n"
"\"Using %s-PW for login, %s-PW for S&F.\"\n"
"\"userpw.bcm has only %d lines!\"\n"
"\"HADR Statistics:\"\n"
"\"Lifetime %s: %d (min=%d) days.\\n\"\n"
"\"Can't kill: Task-ID not found, or own task.\\n\"\n"
"\"Board created.\\n\"\n"
"\"Main board not found.\\n\"\n"
"\"Too many boards.\\n\"\n"
"\"Boardname exists.\\n\"\n"
"\"Invalid boardname.\\n\"\n"
"\"Board removed.\\n\"\n"
"\"Board not found.\\n\"\n"
"\"Board is not empty.\\n\"\n"
"\"Board moved.\\n\"\n"
"\"New mainboard not found.\\n\"\n"
"\"Old board not found.\\n\"\n"
"\"Starting telephone forward to %s (%s).\\n\"\n"
"\"No modem selected\"\n"
"\"No TTYDEVICE active\\n\"\n"
"\"Hang up modem.\\n\"\n"
"\"TTY already active\"\n"
"\"Monitor: invalid Task-ID.\\n\"\n"
"\"Monitor: task monitor busy.\\n\"\n"
"\"Monitor: task %d (%s):\\n\"\n"
"\"Monitor: data discarded due to buffer congestion.\"\n"
"\"Monitor: server task died.\\n\"\n"
"\"CPU load in 5sec-intervals:\\n\"\n"
"\"Using new call %s.\\n\"\n"
"\"marked unread\"\n"
"\"Starting DIDADIT-Download\\n\"\n"
"\"Starting BINSPLIT-Download\\n\"\n"
"\"BIN-TX aborted\\n\"\n"
"\"Sysop only.\\n\"\n"
"\"No POCSAG group active.\\n\"\n"
"\"Users: %4d\\n\"\n"
"\"Sorry, POCSAG server not enabled.\\n\"\n"
"\"No user %s in the group.\\n\"\n"
"\"Name of the group: %s\\n\"\n"
"\"Description: %s\\n\"\n"
"\"Description of the group: %s\\n\"\n"
"\"Users (%d):\\n\"\n"
"\"New description of group %s:\\n%s\\n\"\n"
"\"%s removed.\\n\"\n"
"\"%s already exists.\\n\"\n"
"\"%s has been created.\\n\"\n"
"\"A group named %s does not exist.\\n\"\n"
"\"%s is already a user of the group %s.\\n\"\n"
"\"You are already a user of the group %s.\\n\"\n"
"\"%s is now a user of the group %s.\\n\"\n"
"\"You are now a user of the group %s.\\n\"\n"
"\"User %s has been deleted from the group %s.\\n\"\n"
"\"You have been deleted from the group %s.\\n\"\n"
"\"No user %s in the group %s.\\n\"\n"
"\"You are not a user of the group %s.\\n\"\n"
"\"Sorry, mailserver not enabled.\\n\"\n"
"\"Sorry, only the maintainer of the group may modify/set this parameter.\\n\"\n"
"\"Invalid number.\\n\"\n"
"\"Options of group %s set to \\\"%s\\\".\\n\"\n"
"\"Options of group %s deleted.\\n\"\n"
"\"The next mail number of the group %s has been set to %s.\\n\"\n"
"\"%s is now a maintainer of the group %s.\\n\"\n"
"\"%s is already a maintainer of the group %s.\\n\"\n"
"\"User %s is no longer a maintainer of the group %s.\\n\"\n"
"\"%s is not a maintainer of the group %s.\\n\"\n"
"\"Users: %4d, Maintainers: %4d\\n\"\n"
"\"Next mail number: %s\\n\"\n"
"\"Options:\"\n"
"\"Maintainer: %d\\n\"\n"
"\"Away endtime disabled.\\n\"\n"
"\"Away endtime set: %s\\n\"\n"
"\"Away is disabled, no away endtime set.\\n\"\n"
"\"Away function enabled with this message:\\n\"\n"
"\"Away function disabled.\\n\"\n"
"\"Away message too long.\\n\"\n"
"\"Notification disabled.\\n\"\n"
"\"Notification call invalid.\\n\"\n"
"\"Notification enabled for call %s.\\n\"\n"
"\"Zip-Code set: %s\\n\"\n"
"\"Zip-Code too long\\n\"\n"
"\"QTH set: %s\\n\"\n"
"\"QTH too long\\n\"\n"
"\"New call removed.\\n\"\n"
"\"New call invalid.\\n\"\n"
"\"New call %s stored.\\n\"\n"
"\"Dirformat %d saved.\\n\"\n"
"\"Really no linefeeds.\\n\"\n"
"\"Valid range for Paclen is %i-%i.\\n\"\n"
"\"TTYPW disabled.\\n\"\n"
"\"TTYPW ok.\\n\"\n"
"\"TTYPW may only have up to 8 characters.\\n\"\n"
"\"Feature not included.\\n\"\n"
"\"LINUXPW is already set. Nothing done.\\n\"\n"
"\"LINUXPW ok.\\n\"\n"
"\"LINUXPW may only have up to 8 characters.\\n\"\n"
"\"Huffman COMPression is now activated\\n\"\n"
"\"Huffman COMPression is now deactivated\\n\"\n"
"\"NOPURGE 1 (purge disabled)\\n\"\n"
"\"NOPURGE 0 (purge enabled)\\n\"\n"
"\"Disable with 0.\\n\"\n"
"\"%s deleted.\\n\"\n"
"\"Unsecure SMTP 1 (No POP before SMTP needed).\\n\"\n"
"\"Unsecure SMTP 0 (Needs POP before SMTP).\\n\"\n"
"\"ECHO 1 (ON).\\n\"\n"
"\"ECHO 0 (OFF).\\n\"\n"
"\"Using %s-PW for login, %s-PW for S&F.\"\n"
"\"Command not possible for guest.\\n\"\n"
"\"Error: no password set.\\n\"\n"
"\"Password disabled.\\n\"\n"
"\"MYBBS is not set to %s\\n\"\n"
"\"User-FWD disabled.\\n\"\n"
"\"User-FWD: PASSIVE.\\n\"\n"
"\"User-FWD connect path set to \\\"%s\\\"\\n\"\n"
"\"AX25-login-password inactive.\\n\"\n"
"\"Password-type for AX25-logins set to %s.\\n\"\n"
"\"S&F-password inactive.\\n\"\n"
"\"Password-type for S&F set to %s.\\n\"\n"
"\"Binary parts of mails will be sent using the\"\n"
"\"protocol.\\n\"\n"
"\"FBBCheckmode 1 (ON).\\n\"\n"
"\"FBBCheckmode 0 (OFF).\\n\"\n"
"\"(Sysop selection)\"\n"
"\"(Frames, no CSS)\"\n"
"\"(no Frames, CSS)\"\n"
"\"(no Frames, no CSS)\"\n"
"\"saved.\\n\"\n"
"\"Other logs\"\n"
"\"Current Log\"\n"
"\"User-Log\"\n"
"\"Forward-Log\"\n"
"\"Go up\"\n"
"\"Go back\"\n"
"\"Send Message\"\n"
"\"Clear Form\"\n"
"\"Read next mail\"\n"
"\"Read previous mail\"\n"
"\"Erase\"\n"
"\"Erase+Reply\"\n"
"\"Comment with text\"\n"
"\"Comment\"\n"
"\"Reply with text\"\n"
"\"Reply\"\n"
"\"Subject\"\n"
"\"Lifetime (1..999)\"\n"
"\"To\"\n"
"\"end dummy\\n\"\n";
#endif
